spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/unit?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false}
    username: ${DB_USERNAME:unit}
    password: ${DB_PASSWORD:unit}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_MAX_SIZE:10}
      minimum-idle: ${DB_POOL_MIN_IDLE:2}
      connection-timeout: ${DB_CONNECTION_TIMEOUT_MS:3000}
      validation-timeout: ${DB_VALIDATION_TIMEOUT_MS:2000}

  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:true}

  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations:
      - ${FLYWAY_LOCATIONS:classpath:db/migration}
      - classpath:db/seed/local
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:false}

  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${SMTP_AUTH:false}
          starttls:
            enable: ${SMTP_STARTTLS_ENABLE:false}
            required: ${SMTP_STARTTLS_REQUIRED:false}

logging:
  level:
    com.unit: ${APP_LOG_LEVEL:DEBUG}
    org.hibernate.SQL: ${HIBERNATE_SQL_LOG_LEVEL:DEBUG}
#    org.hibernate.orm.jdbc.bind: ${HIBERNATE_BIND_LOG_LEVEL:TRACE}

unit:
  security:
    jwt:
      issuer: ${JWT_ISSUER:unit}
      secret: ${JWT_SECRET:local-dev-secret-must-be-at-least-32-bytes}
      access-token-expiration-seconds: ${JWT_ACCESS_TOKEN_EXPIRATION_SECONDS:1800}
    refresh-token:
      expiration-seconds: ${REFRESH_TOKEN_EXPIRATION_SECONDS:1209600} # 14일
    email-encryption:
      key-base64: ${EMAIL_ENCRYPTION_KEY_BASE64:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=}

  mail:
    enabled: ${MAIL_ENABLED:false}
    from-address: ${MAIL_FROM_ADDRESS:no-reply@unit.local}
    from-name: ${MAIL_FROM_NAME:UniTT}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
